using ConsoleApp2.Player;
using ConsoleApp2.Squares;

namespace ConsoleApp2;

/// <summary>
/// Represents a single possible action a player can take during their turn.
/// 
/// A Move is a value object:
/// - It does NOT modify game state
/// - It only describes an intended action
/// 
/// Moves are generated by the MoveGenerator and then
/// validated and applied by the Game class.
/// </summary>
public class Move
{
    public int PieceIndex { get; init; }
    /// <summary>
    /// Relative movement distance from the piece's current square.
    /// 
    /// Examples:
    ///  - Delta = 0 → stay on the same square
    ///  - Delta = 3 → move forward 3 squares
    ///  - Delta = -2 → move backward 2 squares
    public int Delta { get; init; }
    /// <summary>
    /// Indicates whether the player chooses to eat carrots
    /// instead of moving.
    /// 
    /// When true, the piece remains on the same square
    /// and carrots are gained according to game rules.
    /// </summary>
    public bool EatCarrots { get; init; }
    /// <summary>
    /// Returns a short, human-readable description of the move.
    /// 
    /// Used primarily for:
    ///  - Console menus
    ///  - Debug output
    /// </summary>
    /// <returns>Simple text description of the move</returns>
    public override string ToString()
    {
        if (EatCarrots)
            return $"Piece {PieceIndex}: Eat carrots (stay)";

        return $"Piece {PieceIndex}: Move {Delta} squares";
    }
    /// <summary>
    /// Returns a detailed description of the move in the context
    /// of the current game state.
    /// 
    /// This includes:
    ///  - Starting square
    ///  - Target square
    ///  - Movement cost in carrots
    /// 
    /// NOTE:
    /// This method is for display purposes only and
    /// must NOT be used to apply game logic.
    /// </summary>
    /// <param name="player">Player performing the move</param>
    /// <returns>Detailed description string</returns>
    public string Describe(PlayerBase player)
    {
        var piece = player.Pieces[PieceIndex];
        int from = piece.CurrentSquare;
        int to = from + Delta;

        if (EatCarrots)
            return $"Piece {PieceIndex}: Eat carrots (stay on {from})";

        return $"Piece {PieceIndex}: {from} → {to} (cost {(Math.Abs(Delta)*(Math.Abs(Delta)+1))/2})";
    }

}

